### ISSUE TITLE
Poor performance when viewing pages with many errors

### ISSUE THREAD

**Issue by frank-borkin** [codeclimate/codeclimate-csslint#12]
Sorry, I don't see a "site" repo to open this in.
When opening https://codeclimate.com/github/frank-borkin/ga-pg/www/css/index.css it takes 60+ seconds and 100% CPU.
Chrome says it's spending most of that time running self.prism.highlightAll and self.prism.highlightElement

Thanks

**Comment by pbrisbin** [comment]
We've made a number of fixes in this area and the page is loading OK for me now. Feel free to re-open (or reach out via [support](https://codeclimate.com/help)) if you still encounter problems.
