### ISSUE TITLE
csslint doesn't respect exclude_paths

### ISSUE THREAD

**Issue by frank-borkin** [codeclimate/codeclimate-csslint#13]
Files specifically excluded in https://github.com/frank-borkin/ga-pg/blob/master/.codeclimate.yml still appear in https://codeclimate.com/github/frank-borkin/ga-pg/issues

js files which previously appeared as issues disappeared once added to exclude_paths, but the css files are still there.

Thanks

**Comment by pbrisbin** [comment]
Hi @frank-borkin. As reported in your other issues, there were some bugs in early versions of this engine and after running an analysis on the latest version, things look a lot better. Can you confirm, is this exclusion problem is still occurring presently?

**Comment by pbrisbin** [comment]
I just look through the issues on the repository and did not find any on excluded files, so I believe this is fixed. Feel free to re-open if not.
