### ISSUE TITLE
csslint attempts to lint files that are not .css files

### ISSUE THREAD

**Issue by deltamualpha** [codeclimate/codeclimate-csslint#14]
```
== node_modules/babel-eslint/node_modules/babel-core/node_modules/convert-source-map/test/fixtures/map-file-comment-inline.css (680 issues) ==
1: Unexpected token '-' at line 1, col 1. [csslint]
1: Unexpected token '#' at line 1, col 1. [csslint]
...
== package.json (680 issues) ==
1: Unexpected token '-' at line 1, col 1. [csslint]
1: Unexpected token '#' at line 1, col 1. [csslint]
...
Analysis complete! Found 8,160 issues.
```

csslint is very, very eager to lint my files. A little... too eager. This output was generated by https://github.com/deltamualpha/metalsmith-collection-tags (after switching csslint to `enabled: true`). It's also ignoring `exclude_paths` (as mentioned in #13).

**Comment by pbrisbin** [comment]
@deltamualpha I've released a new csslint image to dockerhub. Please let me know if this problem persists after updating. Sorry for the delay.
