### ISSUE TITLE
Push updated image to dockerhub

### ISSUE THREAD

**Issue by mikebryant** [codeclimate/codeclimate-csslint#15]
The root cause of #13 and #14 (when running in the codeclimate cli) is that the current image on dockerhub is based on 735a1efcc017ff111d073c6bb359df64ea6f0a47
The fixes for these issues are a couple of commits later, in 6187fb668149a6a7cdc1760a2809fd102a6af3f8

Pushing the latest image so it's available for the cli should fix this.

**Comment by pbrisbin** [comment]
I've pushed new image to dockerhub based on current master. Thanks for the headsup and sorry for the oversight (and delay in correcting)!
