### ISSUE TITLE
This engine shows wrong lines of css-code or doesn't show any

### ISSUE THREAD

**Issue by zeird** [codeclimate/codeclimate-csslint#16]
For example, see the results for [this file](https://codeclimate.com/github/zeird/godville-ui-plus/source/forum.css) (and a [screenshot of what I see](https://i.imgur.com/zWTmmQ3.png)).

**Comment by pbrisbin** [comment]
Hi @zeird we did have a bug previously that would report issues in the wrong file, which could've certainly caused what you see in your screenshot. Following the source link appears to be showing things correctly now -- are you still seeing this issue?

**Comment by zeird** [comment]
Yep, It seems like an issue with linenumbers is fixed now.
