### ISSUE TITLE
Unknown svg properties false-positive

### ISSUE THREAD

**Issue by apank** [codeclimate/codeclimate-csslint#30]
![unknown](https://cloud.githubusercontent.com/assets/6688699/13299193/1876a77c-db08-11e5-80f7-21ca10aff5b8.jpg)

**Comment by ABaldwinHunter** [comment]
Hi @apank thanks for opening this issue!

As you [noted](https://github.com/CSSLint/csslint/issues/641) on the CSSLint/csslint repo itself, this issue stems from a behavior of the native tool that our engine wraps.

We're aware of the issue and have implementing a fix on our roadmap.

**Comment by ustroetz** [comment]
Any updates here?

**Comment by pbrisbin** [comment]
Thanks for the bump @ustroetz, it looks like the fix to csslint was merged, so hopefully all we'll have to do is update the version the engine runs to get the fix on our side. Hopefully we can get to this this week. If you're open making that change yourself in a PR, that could speed things up.

**Comment by apank** [comment]
any update?

**Comment by GordonDiggs** [comment]
@apank @ustroetz I just released an updated version of the engine that should fix this! Let me know if you are still having issues and we can reopen this.

**Comment by jakeleboeuf** [comment]
Hey folks- hopping on this same thread with additional properties that need to be added. I'm currently running into the following, but might as well support the [full list](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute)?

`cx`, `cy`, `r`
